/*
Copyright 2022 ByteDance and its affiliates.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	proxyv1alpha1 "github.com/kubewharf/kubegateway/pkg/apis/proxy/v1alpha1"
	internalinterfaces "github.com/kubewharf/kubegateway/pkg/client/informers/internalinterfaces"
	kubernetes "github.com/kubewharf/kubegateway/pkg/client/kubernetes"
	v1alpha1 "github.com/kubewharf/kubegateway/pkg/client/listers/proxy/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RateLimitConditionInformer provides access to a shared informer and lister for
// RateLimitConditions.
type RateLimitConditionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RateLimitConditionLister
}

type rateLimitConditionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewRateLimitConditionInformer constructs a new informer for RateLimitCondition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRateLimitConditionInformer(client kubernetes.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRateLimitConditionInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredRateLimitConditionInformer constructs a new informer for RateLimitCondition type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRateLimitConditionInformer(client kubernetes.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ProxyV1alpha1().RateLimitConditions().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ProxyV1alpha1().RateLimitConditions().Watch(context.TODO(), options)
			},
		},
		&proxyv1alpha1.RateLimitCondition{},
		resyncPeriod,
		indexers,
	)
}

func (f *rateLimitConditionInformer) defaultInformer(client kubernetes.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRateLimitConditionInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *rateLimitConditionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&proxyv1alpha1.RateLimitCondition{}, f.defaultInformer)
}

func (f *rateLimitConditionInformer) Lister() v1alpha1.RateLimitConditionLister {
	return v1alpha1.NewRateLimitConditionLister(f.Informer().GetIndexer())
}
