//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 ByteDance and its affiliates.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientConfig) DeepCopyInto(out *ClientConfig) {
	*out = *in
	if in.BearerToken != nil {
		in, out := &in.BearerToken, &out.BearerToken
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.KeyData != nil {
		in, out := &in.KeyData, &out.KeyData
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.CertData != nil {
		in, out := &in.CertData, &out.CertData
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.CAData != nil {
		in, out := &in.CAData, &out.CAData
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientConfig.
func (in *ClientConfig) DeepCopy() *ClientConfig {
	if in == nil {
		return nil
	}
	out := new(ClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchPolicy) DeepCopyInto(out *DispatchPolicy) {
	*out = *in
	if in.UpsteamSubset != nil {
		in, out := &in.UpsteamSubset, &out.UpsteamSubset
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]DispatchPolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchPolicy.
func (in *DispatchPolicy) DeepCopy() *DispatchPolicy {
	if in == nil {
		return nil
	}
	out := new(DispatchPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DispatchPolicyRule) DeepCopyInto(out *DispatchPolicyRule) {
	*out = *in
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.APIGroups != nil {
		in, out := &in.APIGroups, &out.APIGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResourceNames != nil {
		in, out := &in.ResourceNames, &out.ResourceNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ServiceAccounts != nil {
		in, out := &in.ServiceAccounts, &out.ServiceAccounts
		*out = make([]ServiceAccountRef, len(*in))
		copy(*out, *in)
	}
	if in.UserGroups != nil {
		in, out := &in.UserGroups, &out.UserGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NonResourceURLs != nil {
		in, out := &in.NonResourceURLs, &out.NonResourceURLs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DispatchPolicyRule.
func (in *DispatchPolicyRule) DeepCopy() *DispatchPolicyRule {
	if in == nil {
		return nil
	}
	out := new(DispatchPolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExemptFlowControlSchema) DeepCopyInto(out *ExemptFlowControlSchema) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExemptFlowControlSchema.
func (in *ExemptFlowControlSchema) DeepCopy() *ExemptFlowControlSchema {
	if in == nil {
		return nil
	}
	out := new(ExemptFlowControlSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowControl) DeepCopyInto(out *FlowControl) {
	*out = *in
	if in.Schemas != nil {
		in, out := &in.Schemas, &out.Schemas
		*out = make([]FlowControlSchema, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowControl.
func (in *FlowControl) DeepCopy() *FlowControl {
	if in == nil {
		return nil
	}
	out := new(FlowControl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowControlSchema) DeepCopyInto(out *FlowControlSchema) {
	*out = *in
	in.FlowControlSchemaConfiguration.DeepCopyInto(&out.FlowControlSchemaConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowControlSchema.
func (in *FlowControlSchema) DeepCopy() *FlowControlSchema {
	if in == nil {
		return nil
	}
	out := new(FlowControlSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowControlSchemaConfiguration) DeepCopyInto(out *FlowControlSchemaConfiguration) {
	*out = *in
	if in.Exempt != nil {
		in, out := &in.Exempt, &out.Exempt
		*out = new(ExemptFlowControlSchema)
		**out = **in
	}
	if in.MaxRequestsInflight != nil {
		in, out := &in.MaxRequestsInflight, &out.MaxRequestsInflight
		*out = new(MaxRequestsInflightFlowControlSchema)
		**out = **in
	}
	if in.TokenBucket != nil {
		in, out := &in.TokenBucket, &out.TokenBucket
		*out = new(TokenBucketFlowControlSchema)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowControlSchemaConfiguration.
func (in *FlowControlSchemaConfiguration) DeepCopy() *FlowControlSchemaConfiguration {
	if in == nil {
		return nil
	}
	out := new(FlowControlSchemaConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfig) DeepCopyInto(out *LoggingConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfig.
func (in *LoggingConfig) DeepCopy() *LoggingConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaxRequestsInflightFlowControlSchema) DeepCopyInto(out *MaxRequestsInflightFlowControlSchema) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaxRequestsInflightFlowControlSchema.
func (in *MaxRequestsInflightFlowControlSchema) DeepCopy() *MaxRequestsInflightFlowControlSchema {
	if in == nil {
		return nil
	}
	out := new(MaxRequestsInflightFlowControlSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReferecence) DeepCopyInto(out *SecretReferecence) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReferecence.
func (in *SecretReferecence) DeepCopy() *SecretReferecence {
	if in == nil {
		return nil
	}
	out := new(SecretReferecence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecureServing) DeepCopyInto(out *SecureServing) {
	*out = *in
	if in.KeyData != nil {
		in, out := &in.KeyData, &out.KeyData
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.CertData != nil {
		in, out := &in.CertData, &out.CertData
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.ClientCAData != nil {
		in, out := &in.ClientCAData, &out.ClientCAData
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecureServing.
func (in *SecureServing) DeepCopy() *SecureServing {
	if in == nil {
		return nil
	}
	out := new(SecureServing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountRef) DeepCopyInto(out *ServiceAccountRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountRef.
func (in *ServiceAccountRef) DeepCopy() *ServiceAccountRef {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenBucketFlowControlSchema) DeepCopyInto(out *TokenBucketFlowControlSchema) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenBucketFlowControlSchema.
func (in *TokenBucketFlowControlSchema) DeepCopy() *TokenBucketFlowControlSchema {
	if in == nil {
		return nil
	}
	out := new(TokenBucketFlowControlSchema)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamCluster) DeepCopyInto(out *UpstreamCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamCluster.
func (in *UpstreamCluster) DeepCopy() *UpstreamCluster {
	if in == nil {
		return nil
	}
	out := new(UpstreamCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpstreamCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamClusterList) DeepCopyInto(out *UpstreamClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpstreamCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamClusterList.
func (in *UpstreamClusterList) DeepCopy() *UpstreamClusterList {
	if in == nil {
		return nil
	}
	out := new(UpstreamClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpstreamClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamClusterServer) DeepCopyInto(out *UpstreamClusterServer) {
	*out = *in
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamClusterServer.
func (in *UpstreamClusterServer) DeepCopy() *UpstreamClusterServer {
	if in == nil {
		return nil
	}
	out := new(UpstreamClusterServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamClusterSpec) DeepCopyInto(out *UpstreamClusterSpec) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make([]UpstreamClusterServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ClientConfig.DeepCopyInto(&out.ClientConfig)
	in.SecureServing.DeepCopyInto(&out.SecureServing)
	in.FlowControl.DeepCopyInto(&out.FlowControl)
	if in.DispatchPolicies != nil {
		in, out := &in.DispatchPolicies, &out.DispatchPolicies
		*out = make([]DispatchPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Logging = in.Logging
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamClusterSpec.
func (in *UpstreamClusterSpec) DeepCopy() *UpstreamClusterSpec {
	if in == nil {
		return nil
	}
	out := new(UpstreamClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamClusterStatus) DeepCopyInto(out *UpstreamClusterStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamClusterStatus.
func (in *UpstreamClusterStatus) DeepCopy() *UpstreamClusterStatus {
	if in == nil {
		return nil
	}
	out := new(UpstreamClusterStatus)
	in.DeepCopyInto(out)
	return out
}
