#!/bin/bash

# Copyright 2022 ByteDance and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function resolve_platform() {
    local platforms=(${MAKE_RULES_GO_BUILD_PLATFORMS[@]})
    local platform="$(go env GOHOSTOS)/$(go env GOHOSTARCH)"
    if [[ ${#platforms[@]} -ge 1 ]]; then
        platform="${platforms[0]}"
    fi
    echo "${platform//\//_}"
}

output="${MAKE_RULES_WORKSPACE}/output"
platform=$(resolve_platform)
echo "resolved platform is ${platform}"

bin="${MAKE_RULES_WORKSPACE}/bin/${platform}"

if [[ -d ${bin} ]]; then
    bins=($(ls ${bin}))
    if [[ ${#bins[@]} -eq 0 ]]; then
        echo "no binary to copy"
        exit 0
    fi
    echo "copying binary to output"
    cp -r ${bin}/* ${output}/
fi
