/*
Copyright 2022 ByteDance and its affiliates.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubewharf/kubegateway/pkg/apis/proxy/v1alpha1"
	scheme "github.com/kubewharf/kubegateway/pkg/client/kubernetes/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RateLimitConditionsGetter has a method to return a RateLimitConditionInterface.
// A group's client should implement this interface.
type RateLimitConditionsGetter interface {
	RateLimitConditions() RateLimitConditionInterface
}

// RateLimitConditionInterface has methods to work with RateLimitCondition resources.
type RateLimitConditionInterface interface {
	Create(ctx context.Context, rateLimitCondition *v1alpha1.RateLimitCondition, opts v1.CreateOptions) (*v1alpha1.RateLimitCondition, error)
	Update(ctx context.Context, rateLimitCondition *v1alpha1.RateLimitCondition, opts v1.UpdateOptions) (*v1alpha1.RateLimitCondition, error)
	UpdateStatus(ctx context.Context, rateLimitCondition *v1alpha1.RateLimitCondition, opts v1.UpdateOptions) (*v1alpha1.RateLimitCondition, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.RateLimitCondition, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RateLimitConditionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RateLimitCondition, err error)
	Acquire(ctx context.Context, rateLimitConditionName string, rateLimitAcquire *v1alpha1.RateLimitAcquire, opts v1.CreateOptions) (*v1alpha1.RateLimitAcquire, error)

	RateLimitConditionExpansion
}

// rateLimitConditions implements RateLimitConditionInterface
type rateLimitConditions struct {
	client rest.Interface
}

// newRateLimitConditions returns a RateLimitConditions
func newRateLimitConditions(c *ProxyV1alpha1Client) *rateLimitConditions {
	return &rateLimitConditions{
		client: c.RESTClient(),
	}
}

// Get takes name of the rateLimitCondition, and returns the corresponding rateLimitCondition object, and an error if there is any.
func (c *rateLimitConditions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RateLimitCondition, err error) {
	result = &v1alpha1.RateLimitCondition{}
	err = c.client.Get().
		Resource("ratelimitconditions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RateLimitConditions that match those selectors.
func (c *rateLimitConditions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RateLimitConditionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RateLimitConditionList{}
	err = c.client.Get().
		Resource("ratelimitconditions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rateLimitConditions.
func (c *rateLimitConditions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("ratelimitconditions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a rateLimitCondition and creates it.  Returns the server's representation of the rateLimitCondition, and an error, if there is any.
func (c *rateLimitConditions) Create(ctx context.Context, rateLimitCondition *v1alpha1.RateLimitCondition, opts v1.CreateOptions) (result *v1alpha1.RateLimitCondition, err error) {
	result = &v1alpha1.RateLimitCondition{}
	err = c.client.Post().
		Resource("ratelimitconditions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rateLimitCondition).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a rateLimitCondition and updates it. Returns the server's representation of the rateLimitCondition, and an error, if there is any.
func (c *rateLimitConditions) Update(ctx context.Context, rateLimitCondition *v1alpha1.RateLimitCondition, opts v1.UpdateOptions) (result *v1alpha1.RateLimitCondition, err error) {
	result = &v1alpha1.RateLimitCondition{}
	err = c.client.Put().
		Resource("ratelimitconditions").
		Name(rateLimitCondition.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rateLimitCondition).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *rateLimitConditions) UpdateStatus(ctx context.Context, rateLimitCondition *v1alpha1.RateLimitCondition, opts v1.UpdateOptions) (result *v1alpha1.RateLimitCondition, err error) {
	result = &v1alpha1.RateLimitCondition{}
	err = c.client.Put().
		Resource("ratelimitconditions").
		Name(rateLimitCondition.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rateLimitCondition).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the rateLimitCondition and deletes it. Returns an error if one occurs.
func (c *rateLimitConditions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("ratelimitconditions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rateLimitConditions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("ratelimitconditions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched rateLimitCondition.
func (c *rateLimitConditions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RateLimitCondition, err error) {
	result = &v1alpha1.RateLimitCondition{}
	err = c.client.Patch(pt).
		Resource("ratelimitconditions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Acquire takes the representation of a rateLimitAcquire and creates it.  Returns the server's representation of the rateLimitAcquire, and an error, if there is any.
func (c *rateLimitConditions) Acquire(ctx context.Context, rateLimitConditionName string, rateLimitAcquire *v1alpha1.RateLimitAcquire, opts v1.CreateOptions) (result *v1alpha1.RateLimitAcquire, err error) {
	result = &v1alpha1.RateLimitAcquire{}
	err = c.client.Post().
		Resource("ratelimitconditions").
		Name(rateLimitConditionName).
		SubResource("acquire").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rateLimitAcquire).
		Do(ctx).
		Into(result)
	return
}
