/*
Copyright 2022 ByteDance and its affiliates.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/kubewharf/kubegateway/pkg/apis/proxy/v1alpha1"
	scheme "github.com/kubewharf/kubegateway/pkg/client/kubernetes/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// UpstreamClustersGetter has a method to return a UpstreamClusterInterface.
// A group's client should implement this interface.
type UpstreamClustersGetter interface {
	UpstreamClusters() UpstreamClusterInterface
}

// UpstreamClusterInterface has methods to work with UpstreamCluster resources.
type UpstreamClusterInterface interface {
	Create(ctx context.Context, upstreamCluster *v1alpha1.UpstreamCluster, opts v1.CreateOptions) (*v1alpha1.UpstreamCluster, error)
	Update(ctx context.Context, upstreamCluster *v1alpha1.UpstreamCluster, opts v1.UpdateOptions) (*v1alpha1.UpstreamCluster, error)
	UpdateStatus(ctx context.Context, upstreamCluster *v1alpha1.UpstreamCluster, opts v1.UpdateOptions) (*v1alpha1.UpstreamCluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.UpstreamCluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.UpstreamClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UpstreamCluster, err error)
	UpstreamClusterExpansion
}

// upstreamClusters implements UpstreamClusterInterface
type upstreamClusters struct {
	client rest.Interface
}

// newUpstreamClusters returns a UpstreamClusters
func newUpstreamClusters(c *ProxyV1alpha1Client) *upstreamClusters {
	return &upstreamClusters{
		client: c.RESTClient(),
	}
}

// Get takes name of the upstreamCluster, and returns the corresponding upstreamCluster object, and an error if there is any.
func (c *upstreamClusters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.UpstreamCluster, err error) {
	result = &v1alpha1.UpstreamCluster{}
	err = c.client.Get().
		Resource("upstreamclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of UpstreamClusters that match those selectors.
func (c *upstreamClusters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.UpstreamClusterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.UpstreamClusterList{}
	err = c.client.Get().
		Resource("upstreamclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested upstreamClusters.
func (c *upstreamClusters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("upstreamclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a upstreamCluster and creates it.  Returns the server's representation of the upstreamCluster, and an error, if there is any.
func (c *upstreamClusters) Create(ctx context.Context, upstreamCluster *v1alpha1.UpstreamCluster, opts v1.CreateOptions) (result *v1alpha1.UpstreamCluster, err error) {
	result = &v1alpha1.UpstreamCluster{}
	err = c.client.Post().
		Resource("upstreamclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(upstreamCluster).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a upstreamCluster and updates it. Returns the server's representation of the upstreamCluster, and an error, if there is any.
func (c *upstreamClusters) Update(ctx context.Context, upstreamCluster *v1alpha1.UpstreamCluster, opts v1.UpdateOptions) (result *v1alpha1.UpstreamCluster, err error) {
	result = &v1alpha1.UpstreamCluster{}
	err = c.client.Put().
		Resource("upstreamclusters").
		Name(upstreamCluster.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(upstreamCluster).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *upstreamClusters) UpdateStatus(ctx context.Context, upstreamCluster *v1alpha1.UpstreamCluster, opts v1.UpdateOptions) (result *v1alpha1.UpstreamCluster, err error) {
	result = &v1alpha1.UpstreamCluster{}
	err = c.client.Put().
		Resource("upstreamclusters").
		Name(upstreamCluster.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(upstreamCluster).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the upstreamCluster and deletes it. Returns an error if one occurs.
func (c *upstreamClusters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("upstreamclusters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *upstreamClusters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("upstreamclusters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched upstreamCluster.
func (c *upstreamClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.UpstreamCluster, err error) {
	result = &v1alpha1.UpstreamCluster{}
	err = c.client.Patch(pt).
		Resource("upstreamclusters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
